"""empty message

Revision ID: 48977441b290
Revises: c295158de7cb
Create Date: 2021-12-02 12:14:18.740758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48977441b290'
down_revision = 'c295158de7cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
